include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/generated/**"
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    dead_code: error

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    discarded_futures: true
    eol_at_end_of_file: true
    flutter_style_todos: true
    leading_newlines_in_multiline_strings: true
    no_default_cases: true
    only_throw_errors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_lambdas: true
    use_build_context_synchronously: true
    use_super_parameters: true
